name: magicpic
channels:
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'appnope=0.1.0=py27_0'
- !!python/unicode
  'astropy=1.3.3=np113py27_0'
- !!python/unicode
  'backports=1.0=py27_0'
- !!python/unicode
  'backports_abc=0.5=py27_0'
- !!python/unicode
  'beautifulsoup4=4.6.0=py27_0'
- !!python/unicode
  'bleach=1.5.0=py27_0'
- !!python/unicode
  'configparser=3.5.0=py27_0'
- !!python/unicode
  'decorator=4.0.11=py27_0'
- !!python/unicode
  'entrypoints=0.2.2=py27_1'
- !!python/unicode
  'enum34=1.1.6=py27_0'
- !!python/unicode
  'functools32=3.2.3.2=py27_0'
- !!python/unicode
  'get_terminal_size=1.0.0=py27_0'
- !!python/unicode
  'html5lib=0.999=py27_0'
- !!python/unicode
  'icu=54.1=0'
- !!python/unicode
  'ipykernel=4.6.1=py27_0'
- !!python/unicode
  'ipython=5.3.0=py27_0'
- !!python/unicode
  'ipython_genutils=0.2.0=py27_0'
- !!python/unicode
  'ipywidgets=6.0.0=py27_0'
- !!python/unicode
  'jinja2=2.9.6=py27_0'
- !!python/unicode
  'jsonschema=2.6.0=py27_0'
- !!python/unicode
  'jupyter=1.0.0=py27_3'
- !!python/unicode
  'jupyter_client=5.1.0=py27_0'
- !!python/unicode
  'jupyter_console=5.1.0=py27_0'
- !!python/unicode
  'jupyter_core=4.3.0=py27_0'
- !!python/unicode
  'markupsafe=0.23=py27_2'
- !!python/unicode
  'mistune=0.7.4=py27_0'
- !!python/unicode
  'mkl=2017.0.3=0'
- !!python/unicode
  'nbconvert=5.2.1=py27_0'
- !!python/unicode
  'nbformat=4.3.0=py27_0'
- !!python/unicode
  'notebook=5.0.0=py27_0'
- !!python/unicode
  'numpy=1.13.0=py27_0'
- !!python/unicode
  'openssl=1.0.2l=0'
- !!python/unicode
  'pandas=0.20.2=np113py27_0'
- !!python/unicode
  'pandocfilters=1.4.1=py27_0'
- !!python/unicode
  'path.py=10.3.1=py27_0'
- !!python/unicode
  'pathlib2=2.2.1=py27_0'
- !!python/unicode
  'pexpect=4.2.1=py27_0'
- !!python/unicode
  'pickleshare=0.7.4=py27_0'
- !!python/unicode
  'pip=9.0.1=py27_1'
- !!python/unicode
  'prompt_toolkit=1.0.14=py27_0'
- !!python/unicode
  'ptyprocess=0.5.1=py27_0'
- !!python/unicode
  'pygments=2.2.0=py27_0'
- !!python/unicode
  'pyqt=5.6.0=py27_2'
- !!python/unicode
  'python=2.7.13=0'
- !!python/unicode
  'python-dateutil=2.6.0=py27_0'
- !!python/unicode
  'pytz=2017.2=py27_0'
- !!python/unicode
  'pywget=2.2=py27_0'
- !!python/unicode
  'pyzmq=16.0.2=py27_0'
- !!python/unicode
  'qt=5.6.2=2'
- !!python/unicode
  'qtconsole=4.3.0=py27_0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'scandir=1.5=py27_0'
- !!python/unicode
  'setuptools=27.2.0=py27_0'
- !!python/unicode
  'simplegeneric=0.8.1=py27_1'
- !!python/unicode
  'singledispatch=3.4.0.3=py27_0'
- !!python/unicode
  'sip=4.18=py27_0'
- !!python/unicode
  'six=1.10.0=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'ssl_match_hostname=3.4.0.2=py27_1'
- !!python/unicode
  'terminado=0.6=py27_0'
- !!python/unicode
  'testpath=0.3.1=py27_0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'tornado=4.5.1=py27_0'
- !!python/unicode
  'traitlets=4.3.2=py27_0'
- !!python/unicode
  'wcwidth=0.1.7=py27_0'
- !!python/unicode
  'wget=1.18=0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'widgetsnbextension=2.0.0=py27_0'
- !!python/unicode
  'zlib=1.2.8=3'
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.14
  - vispy==0.5.0.dev0
prefix: !!python/unicode '//anaconda/envs/magicpic'

